const { chromium } = require('/opt/homebrew/lib/node_modules/omniroute/node_modules/playwright');
const fs=require('node:fs'), path=require('node:path');
const out=process.argv[2]||'initial';
const run='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa', project='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb', zone='cccccccc-cccc-4ccc-8ccc-cccccccccccc';
const uid=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const photo=fs.readFileSync(path.resolve('web/public/demo/Screenshot_87.jpg'));
const inputs=Array.from({length:8},(_,i)=>({input_id:uid(i+10),ordinal:i,sha256:'a'.repeat(64),artifact_id:uid(i+20)}));
const objects=inputs.flatMap((input,i)=>[0,1].map(n=>({id:uid(100+i*2+n),input_id:input.input_id,class_name:'excavator',score:.83,box:n?[.55,.2,.9,.7]:[.1,.3,.45,.8],image_size:[1920,1080],invocation_id:uid(90)})));
const stages=['input_registration','frame_usability','equipment_observation','series_aggregation','rule_evaluation','result_projection'];
const observations=inputs.map(input=>({...input,class_name:'excavator',state:'detected',source_artifact_id:input.artifact_id}));
const completed={run_id:run,project_id:project,purpose:'ordinary',state:'succeeded',stages:stages.map(name=>({name,state:name==='rule_evaluation'?'skipped':'succeeded',reason:name==='rule_evaluation'?'not_applicable':null})),inputs,objects,observations,context:{project_id:project,zone_id:zone,period:'2026-09-26T10:00:00Z',capture_times:inputs.map(()=>'2026-09-26T10:00:00Z')},result_projection:{outcome:'observations_only',frames:observations}};
const proposal={id:uid(200),run_id:run,input_id:inputs[0].input_id,input_sha256:inputs[0].sha256,artifact_id:inputs[0].artifact_id,original_objects:objects.slice(0,2),objects:objects.slice(0,2),revision:1,status:'pending',version_id:uid(201),whole_frame_verified:false,reason:''};
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}),checks=[];
 const check=(name,passed,extra={})=>checks.push({name,passed:!!passed,...extra});
 try{for(const width of (process.env.DIAGNOSTIC ? [320] : [320,390,768,1440])){
  const context=await browser.newContext({viewport:{width,height:1000},hasTouch:true});await context.addInitScript(()=>localStorage.setItem('construction-onboarding','completed'));
  const page=await context.newPage(),errors=[];page.on('pageerror',error=>errors.push(error.message));let state=completed;
  const signals=[{id:uid(301),zone_id:zone,revision_id:uid(400),plan_revision_number:1,work_entry_id:uid(401),state:'new',kind:'expected_equipment_missing',run_id:run,created_at:'2026-09-26T10:00:00Z',comment:'',project_name:'Стройплощадка',zone_name:'Северный участок',work_title:'Разработка котлована',basis:{class_name:'dump_truck',supporting_input_ids:[inputs[1].input_id]},preview:{...inputs[1]}}];
  await context.route('**/api/**',route=>{
   const p=new URL(route.request().url()).pathname.replace('/api','');
   if(p.includes('/artifacts/'))return route.fulfill({contentType:'image/jpeg',body:photo});
   let body=p===`/runs/${run}`?state:p==='/projects'?{projects:[{id:project,name:'Стройплощадка',timezone:'Europe/Moscow'}]}:p.endsWith('/zones')?{zones:[{id:zone,name:'Северный участок'}]}:p.endsWith('/plan')?{revision_id:uid(400),revision_number:1,entries:[{id:uid(401),state:'active',stage_key:'excavation',starts_at:'2026-09-26T08:00:00Z',ends_at:'2026-09-26T18:00:00Z',expected_equipment:['dump_truck']}]}:p==='/signals'?{signals,new_count:1,summary:{open_count:520,attention_count:500,insufficient_data_count:20}}:p==='/admin/session'?{csrf:'csrf'}:p==='/admin/annotations'?{annotations:[proposal],next_offset:null}:p==='/admin/overview'?{cards:{},daily:[],projects:[],funnel:{},wizard:{}}:{runs:[],choices:[]};
   return route.fulfill({contentType:'application/json',body:JSON.stringify(body)});
  });
  const base=`http://127.0.0.1:15175/projects/${project}`;
  const overflow=async(label)=>{const value=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));check(`${width} ${label} overflow`,value.scroll<=value.width+1,value)};
  const screenshot=async(label)=>{if(!process.env.NO_SCREENSHOTS&&!process.env.DIAGNOSTIC&&(width===390||width===1440))await page.screenshot({animations:'disabled',path:path.join(__dirname,`${out}-${width}-${label}.png`),fullPage:true})};
  await page.goto(`${base}/runs/${run}`);await page.getByText('Исправить разметку',{exact:true}).click();await page.locator('.annotation-canvas img').waitFor();await page.locator('.annotation-canvas img').evaluate(image=>image.decode());
  await overflow('editor');check(`${width} eight handles`,await page.locator('.annotation-resize').count()===8);
  await page.getByText('Точные координаты',{exact:true}).click();const left=page.getByLabel('Слева',{exact:true});
  await page.locator('.annotation-box').first().focus();await page.keyboard.press('ArrowRight');check(`${width} keyboard editing`,Number(await left.inputValue())===.11);
  await page.getByRole('button',{name:'Увеличить фото',exact:true}).click();await page.getByRole('button',{name:'Двигать фото',exact:true}).click();
  await page.locator('.annotation-viewport').evaluate(e=>e.scrollIntoView({block:'center'}));let vp=await page.locator('.annotation-viewport').boundingBox();await page.mouse.move(vp.x+vp.width/2,vp.y+60);await page.mouse.down();await page.mouse.move(vp.x+vp.width/2-30,vp.y+45);await page.mouse.up();check(`${width} pan leaves geometry`,Number(await left.inputValue())===.11);
  if(process.env.DIAGNOSTIC)await page.evaluate(()=>{window.pointerLog=[];for(const type of ['pointerdown','pointerup','pointercancel'])document.addEventListener(type,e=>window.pointerLog.push({type,target:e.target.className,x:e.clientX,y:e.clientY}),true)});await page.getByRole('button',{name:'Нарисовать объект',exact:true}).click();await page.locator('.annotation-viewport').evaluate(e=>e.scrollIntoView({block:'center'}));vp=await page.locator('.annotation-viewport').boundingBox();await page.mouse.move(vp.x+vp.width*.8,vp.y+Math.min(vp.height*.7,150));await page.mouse.down();await page.mouse.move(vp.x+vp.width*.6,vp.y+30);await page.mouse.up();if(process.env.DIAGNOSTIC)console.log(JSON.stringify(await page.evaluate(()=>({events:window.pointerLog,canvas:document.querySelector('.annotation-canvas').getBoundingClientRect().toJSON(),viewport:document.querySelector('.annotation-viewport').getBoundingClientRect().toJSON(),objects:document.querySelector('.annotation-objects').textContent,active:document.activeElement.outerHTML})),null,2));check(`${width} reverse draw`,await page.locator('.annotation-objects li').count()===3);await page.waitForFunction(()=>document.querySelector('.annotation-selected select')===document.activeElement,{},{timeout:3000}).catch(()=>{});check(`${width} class focused after draw`,await page.locator('.annotation-selected select').evaluate(e=>e===document.activeElement));
  await page.getByRole('button',{name:'Отменить',exact:true}).click();check(`${width} one undo per drag`,await page.locator('.annotation-objects li').count()===2);await page.getByRole('button',{name:'Вписать фото',exact:true}).click();await page.locator('.annotation-viewport').focus();await page.keyboard.press('+');await page.keyboard.press('ArrowRight');check(`${width} keyboard photo pan`,await page.locator('.annotation-canvas').evaluate(e=>e.style.transform.includes('-40px')));await page.keyboard.press('Home');
  await page.locator('.annotation-viewport').evaluate(e=>e.scrollIntoView({block:'center'}));vp=await page.locator('.annotation-viewport').boundingBox();const beforePinch=await page.evaluate(()=>JSON.stringify(Object.entries(localStorage).filter(([key])=>key.startsWith('annotation:')))),cdp=await context.newCDPSession(page),cx=vp.x+vp.width/2,cy=vp.y+60;
  await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:cx-25,y:cy,id:1},{x:cx+25,y:cy,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:cx-45,y:cy,id:1},{x:cx+45,y:cy,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});check(`${width} touch pinch zooms`,await page.getByLabel('Масштаб фото',{exact:true}).textContent()!=='100%');check(`${width} pinch preserves draft`,await page.evaluate(()=>JSON.stringify(Object.entries(localStorage).filter(([key])=>key.startsWith('annotation:'))))===beforePinch);await cdp.detach();await page.getByRole('button',{name:'Вписать фото',exact:true}).click();await screenshot('editor');
  if(width===1440){await page.evaluate(()=>document.documentElement.style.zoom='2');await overflow('editor 200%');await page.evaluate(()=>document.documentElement.style.zoom='')}

  await page.getByRole('button',{name:'Вернуться к результату'}).click();check(`${width} editor return focus`,await page.getByText('Исправить разметку',{exact:true}).evaluate(e=>e===document.activeElement));
  await page.goto(`${base}/signals`);await page.getByRole('button',{name:'Открыть фото',exact:true}).waitFor();await page.locator('.signal-photo img').waitFor();await overflow('signals');check(`${width} server summary`,(await page.getByLabel('Сводка открытых сигналов').textContent()).includes('520'));
  await page.getByLabel('Комментарий',{exact:true}).fill('Проверю на площадке');await page.getByRole('button',{name:'Открыть фото',exact:true}).click();await page.getByRole('dialog').waitFor();await page.getByRole('button',{name:'Увеличить',exact:true}).click();await page.getByRole('button',{name:'Следующий кадр',exact:true}).click();await page.getByLabel('Рамки объектов',{exact:true}).uncheck();await page.keyboard.press('Escape');await page.getByRole('dialog').waitFor({state:'detached'});check(`${width} viewer restores focus`,await page.getByRole('button',{name:'Открыть фото',exact:true}).evaluate(e=>e===document.activeElement));check(`${width} viewer retains comment`,await page.getByLabel('Комментарий',{exact:true}).inputValue()==='Проверю на площадке');await screenshot('signals');
  if(width===1440){await page.evaluate(()=>document.documentElement.style.zoom='2');await overflow('signals 200%');await page.evaluate(()=>document.documentElement.style.zoom='')}
  state={...completed,state:'running',result_projection:null,stages:stages.map((name,i)=>({name,state:i<2?'succeeded':i===2?'running':'pending'}))};await page.goto(`${base}/runs/${run}`);await page.locator('.analysis-scene.is-recognizing').waitFor();await page.locator('.analysis-photo img').waitFor();await overflow('progress');check(`${width} primary photo scene`,await page.locator('.run-workspace').evaluate(e=>e.firstElementChild.classList.contains('analysis-scene')));check(`${width} actual stage title`,await page.locator('.analysis-stage-copy h2').textContent()==='Распознавание техники');check(`${width} six stages`,await page.locator('.analysis-route li').count()===6);await screenshot('progress');
  await page.locator('.analysis-thumbnails button').nth(2).click();state={...state,stages:stages.map((name,i)=>({name,state:i<3?'succeeded':i<5?'skipped':'running',reason:i===3||i===4?'not_applicable':null}))};await page.getByRole('heading',{name:'Формирование результата',exact:true}).waitFor();check(`${width} skipped polls authoritative`,await page.locator('.analysis-route .route-skipped').count()===2);check(`${width} no auto frame switch`,await page.locator('.analysis-thumbnails button').nth(2).getAttribute('aria-pressed')==='true');check(`${width} recognition sweep only`,await page.locator('.analysis-sweep').evaluate(e=>getComputedStyle(e).display==='none'));
  await context.setOffline(true);await page.getByRole('heading',{name:'Связь прервана — проверяем состояние'}).waitFor();check(`${width} disconnected motion stopped`,await page.locator('.analysis-scene').evaluate(e=>[...e.querySelectorAll('*')].every(child=>getComputedStyle(child).animationName==='none')));await context.setOffline(false);await page.emulateMedia({reducedMotion:'reduce'});check(`${width} reduced motion stopped`,await page.locator('.analysis-scene').evaluate(e=>[...e.querySelectorAll('*')].every(child=>getComputedStyle(child).animationName==='none')));await page.emulateMedia({reducedMotion:'no-preference'});
  await page.getByLabel('Движение во время анализа').uncheck();check(`${width} motion toggle stops`,await page.locator('.analysis-scene.is-running').count()===0);
  if(width===1440){await page.evaluate(()=>document.documentElement.style.zoom='2');await overflow('progress 200%');await page.evaluate(()=>document.documentElement.style.zoom='')}
  await page.goto('http://127.0.0.1:15175/admin');await page.getByRole('button',{name:'Разметка',exact:true}).click();await page.getByRole('button',{name:/Кадр .*Версия 1/}).click();await page.locator('.annotation-editor img').evaluate(image=>image.decode());await overflow('owner editor');check(`${width} owner eight handles`,await page.locator('.annotation-resize').count()===8);await page.getByLabel('Проверил весь кадр: все объекты и их границы').check();await page.locator('.annotation-editor select').selectOption('truck');check(`${width} owner edit resets approval`,!await page.getByLabel('Проверил весь кадр: все объекты и их границы').isChecked());await page.getByRole('button',{name:'Вернуться к очереди'}).click();await page.waitForFunction(id=>document.activeElement?.id===`proposal-${id}`,proposal.id);check(`${width} owner return focus`,await page.getByRole('button',{name:/Кадр .*Версия 1/}).evaluate(e=>document.activeElement===e));
  check(`${width} no page errors`,errors.length===0,{errors});await context.close();
 }}finally{await browser.close();fs.writeFileSync(path.join(__dirname,`${out}-checks.json`),JSON.stringify({scope:'Local headless Chromium with deterministic API fixtures; CSS zoom, not toolbar zoom',checks},null,2))}
 const failed=checks.filter(item=>!item.passed);console.log(JSON.stringify({checks:checks.length,failed},null,2));if(failed.length)process.exitCode=1;
})().catch(error=>{console.error(error);process.exit(1)});
