const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
import assert from 'node:assert/strict';
import { mkdir, readFile } from 'node:fs/promises';
const folder = process.argv[2] || '/private/tmp/lzt-annotation-review';
const out = process.argv[3] || '/private/tmp/lzt-annotation-qa';
await mkdir(out, {recursive:true});
const browser = await chromium.launch({headless:true,...(process.env.CHROME_PATH ? {executablePath:process.env.CHROME_PATH} : process.env.PLAYWRIGHT_BROWSER === 'chromium' ? {} : {channel:'chrome'}),args:['--disable-gpu']});
try {
 const page=await browser.newPage({viewport:{width:1440,height:1000}}), errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.goto(`file://${folder}/index.html`);
 await page.waitForFunction(()=>document.querySelector('#photo').naturalWidth>0);
 await page.locator('#reviewer').fill('Тестовый проверяющий');
 await page.locator('#confirm').click();
 await assert.equal(await page.locator('#message').getAttribute('class'),'error');
 for(const select of await page.locator('#classes select, #scenes select').all()) await select.selectOption('absent');
 await page.locator('#workStage').selectOption('unknown');
 const rect=await page.locator('#overlay').boundingBox();
 await page.mouse.move(rect.x+rect.width*.2,rect.y+rect.height*.2);await page.mouse.down();await page.mouse.move(rect.x+rect.width*.5,rect.y+rect.height*.6);await page.mouse.up();
 assert.equal(await page.locator('#boxes .box-row').count(),1);
 assert.equal(await page.locator('#equipment-excavator').inputValue(),'present');
 await page.screenshot({path:`${out}/desktop.png`,fullPage:true});
 await page.locator('#confirm').click();
 assert.match(await page.locator('#progress').innerText(),/подтверждено 1 из 100/);
 await page.reload();await page.waitForFunction(()=>document.querySelector('#photo').naturalWidth>0);
 assert.equal(await page.locator('#boxes .box-row').count(),1);
 assert.match(await page.locator('#progress').innerText(),/подтверждено 1 из 100/);
 const downloadPromise=page.waitForEvent('download');await page.locator('#export').click();const download=await downloadPromise;await download.saveAs(`${out}/review.json`);
 const data=JSON.parse(await readFile(`${out}/review.json`,'utf8'));assert.equal(data.images['organizer-png-001'].review_state,'reviewed');assert.equal(data.images['organizer-png-001'].boxes[0].origin,'human_drawn');
 await page.locator('#notes').fill('Проверить границу');assert.match(await page.locator('#progress').innerText(),/подтверждено 0 из 100/);
 page.once('dialog',dialog=>dialog.accept());await page.locator('#import').setInputFiles(`${out}/review.json`);await page.waitForFunction(()=>document.querySelector('#progress').textContent.includes('подтверждено 1'));
 await page.locator('#jump').selectOption('1');await page.locator('#showCandidates').check();assert.ok(await page.locator('#candidates button').count()>0);await page.locator('#candidates button').first().click();assert.equal(await page.locator('#boxes .box-row').count(),1);assert.equal(await page.locator('#candidates button').first().isDisabled(),true);
 assert.equal(await page.evaluate(()=>validTimestamp('2026-02-31T12:00:00+03:00')),false);
 const bad=structuredClone(data);bad.images['organizer-png-001'].review_state='draft';bad.images['organizer-png-001'].equipment='bad';
 await page.locator('#import').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(bad))});
 await page.waitForFunction(()=>document.querySelector('#message').classList.contains('error'));assert.equal(await page.locator('#boxes .box-row').count(),1);
 await page.setViewportSize({width:390,height:844});const before=(await page.locator('#imageStage').boundingBox()).width;await page.locator('#zoom').selectOption('2');assert.ok((await page.locator('#imageStage').boundingBox()).width>before*1.9);await page.locator('#zoom').selectOption('1');await page.screenshot({path:`${out}/mobile.png`,fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.evaluate(()=>{document.querySelector('#photo').src='images/nonexistent.png'});await page.waitForFunction(()=>document.querySelector('#confirm').disabled);assert.equal(await page.locator('#confirm').isDisabled(),true);assert.deepEqual(errors,[]);
 const freshPage=await browser.newPage();await freshPage.goto(`file://${folder}/index.html`);await freshPage.locator('#workStage').selectOption('unknown');let warned=false;freshPage.once('dialog',async dialog=>{warned=true;await dialog.dismiss()});await freshPage.locator('#import').setInputFiles(`${out}/review.json`);await freshPage.waitForTimeout(100);assert.equal(warned,true);assert.equal(await freshPage.locator('#workStage').inputValue(),'unknown');
 console.log('PASS: draw, explicit labels, confirmation, persistence, export/import, editing invalidation, machine adoption, desktop/mobile, no JS errors');
} finally {await browser.close()}
